"""empty message

Revision ID: 629ee38d376d
Revises: 0f83c225b68d
Create Date: 2022-11-19 23:08:59.652057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629ee38d376d'
down_revision = '0f83c225b68d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
